name:                hChain
version:             0.1.0.0
github:              "higuhi/haskell-blockchain"
license:             MIT
author:              "H4C Hiroshi Higuchi"
maintainer:          "hiroshi.garage.sale@gmail.com"
copyright:           "2020 H4C"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hChain#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- aeson
- cryptonite
- bytestring
 
library:
  source-dirs: src

executables:
  hChain-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hChain

tests:
  hChain-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hChain
